### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by BenjaminGu** [SanderMertens/tower_defense#1]
I ran the command as specified in the README.md and I got a build error as follows.
```
[  clone] 'https://github.com/SanderMertens/tower_defense' into 'C:\Users\Immuno\bake\src\tower_defense'
[  clone] 'https://github.com/flecs-hub/flecs-hub' into 'C:\Users\Immuno\bake\src\flecs-hub'
[  build] application tower_defense => '.'
[     7%] main.cpp
main.cpp
C:\Users\Immuno\bake\include\tower_defense/bake_config.h(21): fatal error C1083: Cannot open include file: '../../deps/flecs.h': No such file or directory
[  error] command returned 2
   cl.exe /nologo /EHsc /Od -D__BAKE__ -D__BAKE__ /D_WINDOWS /D_USRDLL /DCGLM_EXPORTS /DCGLM_DLL /DBAKE_PROJECT_ID=\"tower_defense\" /Dtower_defense_EXPORTS /I C:\Users\Immuno\bake\include /I .\include /c .\src\main.cpp /Fo.bake_cache\x64-Windows-debug\obj\main.obj /Zi
[   from] command for task 'main.cpp' failed
[   from] dependency 'objects' failed
[   from] failed to build rule 'ARTEFACT'
[  error] build interrupted for tower_defense in .
[  error] project tower_defense built with errors
[  error] failed to build '.'
[  error] build failed, cannot run
```

But, flecs.h exists in the proper location.
How can I handle this error?

**Comment by MasterDrake** [comment]
I have a similar problem, where it says that "cl.exe" is not in PATH and it fails.
Woulnd't be better/easier if cmake was used as build generator?

**Comment by guyvert1** [comment]
Maybe the proj. is out of date compared to the build system ? 

I fixed it by editing this file : <user>\bake\src\tower_defense\include\tower_defense\bake_config.h

Changing: 
../../deps
to
../../src/tower_defense/deps

**Comment by SanderMertens** [comment]
Just checked in a fix. It was an issue with bake, the order in which include directories were evaluated on Windows was broken for standalone projects. If you upgrade to the latest bake & try again it should work!
