### ISSUE TITLE
Flecs asserts with missing symbol

### ISSUE THREAD

**Issue by cubeleo** [SanderMertens/tower_defense#2]
I'm running Ubuntu 20.04, and I followed the bake instructions in the tower defense readme.  Here's my output showing the assertion failure:

[  clone] 'https://github.com/SanderMertens/tower_defense' into '/home/adwyer/bake/src/tower_defense'
[  clone] 'https://github.com/flecs-hub/flecs-hub' into '/home/adwyer/bake/src/flecs-hub'
[  build] application tower_defense => '.'
[     7%] main.cpp
./src/main.cpp: In function ‘void AimTarget(flecs::iter&, size_t, Turret&, Target&, Position&)’:
./src/main.cpp:499:38: warning: ‘*’ in boolean context, suggest ‘&&’ instead [-Wint-in-bool-context]
  499 |         target.lock = (r.y == angle) * (distance < TurretRange);
      |                       ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
[    14%] flecs_systems_sokol.c
[    21%] flecs_game.c
[    28%] flecs_components_geometry.c
[    35%] flecs_components_cglm.c
[    42%] flecs_components_transform.c
[    50%] cglm.c
[    57%] flecs_components_gui.c
[    64%] flecs_systems_physics.c
[    71%] flecs_components_physics.c
[    78%] flecs_systems_transform.c
[    85%] flecs.c
[    92%] flecs_components_input.c
[   100%] flecs_components_graphics.c
[    run] application tower_defense [44238] 'bin/x64-Linux-debug/tower_defense'
fatal: flecs.c: 17610: assert: !existing || (sym != NULL) Head (MISSING_SYMBOL)
bin/x64-Linux-debug/tower_defense(+0x150989) [0x55c4c3a60989]
bin/x64-Linux-debug/tower_defense(+0x151058) [0x55c4c3a61058]
bin/x64-Linux-debug/tower_defense(+0x159b26) [0x55c4c3a69b26]
bin/x64-Linux-debug/tower_defense(+0x3838f) [0x55c4c394838f]
bin/x64-Linux-debug/tower_defense(+0x21929) [0x55c4c3931929]
bin/x64-Linux-debug/tower_defense(+0xf1d9) [0x55c4c391f1d9]
bin/x64-Linux-debug/tower_defense(+0x101d4) [0x55c4c39201d4]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7face1096083]
bin/x64-Linux-debug/tower_defense(+0x9f3e) [0x55c4c3919f3e]
[  error] process 44238 exited with signal 6
[   from] process crashed (6)

**Comment by SanderMertens** [comment]
Sorry for the late reply! This looks like a bug in Flecs that was fixed a few versions ago, so I'll close the issue for now (I can build/run the code successfully with the latest flecs). Feel free to open another issue if the problem persists!
